name: _
description: "حارس طفلك الصغير يمنحك راحة البال، فهو درع ذكي يحمي أطفالك من التهديدات الرقمية، ويكتشف المحتوى الضار والرسائل المسيئة، مع إشعارات"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0
  provider: ^6.0.0
  audioplayers: ^6.0.0
  url_launcher: ^6.0.0
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
